import 'package:get/get.dart';

class AlbumScreenModel extends GetxController {
  final List<Map<String, dynamic>> albums = [
    {
      "image": "assets/images/illuminate.jpg",
      "artistName": "Shawn Mendes",
      "albumName": "Illuminate",
      "numberofSongs": 13,
      "songs": [
        "There's Nothing Holdin'Me Back",
        "Ruin",
        "Mercy",
        "Treat You Better",
        "Three Empty Words",
        "Don't Be a Fool",
        "Like This",
        "No Promises",
        "Lights On",
        "Honest",
        "Patience",
        "Bad Reputation",
        "Understand"
      ]
    },
    {
      "image": "assets/images/Lover.png",
      "artistName": "Taylor Swift",
      "albumName": "Lover",
      "numberofSongs": 18,
      "songs": [
        "I Forgot That You Existed",
        "Cruel Summer",
        "Lover",
        "The Man",
        "The Archer",
        "I Think He Knows",
        "Miss Americana & The Heartbreak Prince",
        "Paper Rings",
        "Cornelia Street",
        "Death by a Thousand Cuts",
        "London Boy",
        "Soon You'll Get Better (featuring Dixie Chicks)",
        "False God",
        "You Need to Calm Down",
        "Afterglow",
        "ME! (featuring Brendon Urie of Panic! At The Disco)",
        "It's Nice to Have a Friend",
        "Daylight"
      ]
    },
    {
      "image": "assets/images/sour.jpg",
      "artistName": "Olivia Rodrigo",
      "albumName": "Sour",
      "numberofSongs": 11,
      "songs": [
        "brutal",
        "traitor",
        "drivers license",
        "1 step forward, 3 steps back",
        "deja vu",
        "good 4 u",
        "enough for you",
        "happier",
        "jealousy, jealousy'",
        "favorite crime",
        "hope ur ok",
      ]
    },
    {
      "image": "assets/images/starboy.jpg",
      "artistName": "The Weekend",
      "albumName": "Starboy",
      "numberofSongs": 15,
      "songs": [
        "Starboy (featuring Daft Punk)",
        "Party Monster",
        "False Alarm",
        "Reminder",
        "Rockin'",
        "Secrets",
        "True Colors",
        "Stargirl Interlude (featuring Lana Del Rey)",
        "Sidewalks (featuring Kendrick Lamar)",
        "Six Feet Under",
        "A Lonely Night",
        "Die for You",
        "I Feel It Coming (featuring Daft Punk)",
        "All I Know (featuring Future)",
        "Ordinary Life",
      ]
    },
    {
      "image": "assets/images/justice.png",
      "artistName": "Justin Bieber",
      "albumName": "Justice",
      "numberofSongs": 16,
      "songs": [
        "2 Much",
        "Deserve You",
        "As I Am (featuring Khalid)",
        "Off My Face",
        "Holy (featuring Chance the Rapper)",
        "Unstable (featuring The Kid Laroi)",
        "MLK Interlude",
        "Die For You (featuring Dominic Fike)",
        "Hold On",
        "Somebody",
        "Ghost",
        "Peaches (featuring Daniel Caesar and Giveon)",
        "Love You Different (featuring BEAM)",
        "Loved By You (featuring Burna Boy)",
        "Anyone",
        "Lonely (with benny blanco)",
      ]
    },
    {
      "image": "assets/images/ed_sheeran_divide.png",
      "artistName": "Ed Sheeran",
      "albumName": "Divide",
      "numberofSongs": 16,
      "songs": [
        "Eraser",
        "Castle on the Hill",
        "Dive",
        "Shape of You",
        "Perfect",
        "Galway Girl",
        "Happier",
        "New Man",
        "Hearts Don't Break Around Here",
        "What Do I Know?",
        "How Would You Feel (Paean)",
        "Supermarket Flowers",
        "Barcelona",
        "Bibia Be Ye Ye",
        "Nancy Mulligan",
        "Save Myself"
      ]
    },
    {
      "image": "assets/images/Lover.png",
      "artistName": "Taylor Swift",
      "albumName": "Lover",
      "numberofSongs": 18,
      "songs": [
        "I Forgot That You Existed",
        "Cruel Summer",
        "Lover",
        "The Man",
        "The Archer",
        "I Think He Knows",
        "Miss Americana & The Heartbreak Prince",
        "Paper Rings",
        "Cornelia Street",
        "Death by a Thousand Cuts",
        "London Boy",
        "Soon You'll Get Better (featuring Dixie Chicks)",
        "False God",
        "You Need to Calm Down",
        "Afterglow",
        "ME! (featuring Brendon Urie of Panic! At The Disco)",
        "It's Nice to Have a Friend",
        "Daylight"
      ]
    },
    {
      "image": "assets/images/Lover.png",
      "artistName": "Taylor Swift",
      "albumName": "Lover",
      "numberofSongs": 18,
      "songs": [
        "I Forgot That You Existed",
        "Cruel Summer",
        "Lover",
        "The Man",
        "The Archer",
        "I Think He Knows",
        "Miss Americana & The Heartbreak Prince",
        "Paper Rings",
        "Cornelia Street",
        "Death by a Thousand Cuts",
        "London Boy",
        "Soon You'll Get Better (featuring Dixie Chicks)",
        "False God",
        "You Need to Calm Down",
        "Afterglow",
        "ME! (featuring Brendon Urie of Panic! At The Disco)",
        "It's Nice to Have a Friend",
        "Daylight"
      ]
    },
    {
      "image": "assets/images/Lover.png",
      "artistName": "Taylor Swift",
      "albumName": "Lover",
      "numberofSongs": 18,
      "songs": [
        "I Forgot That You Existed",
        "Cruel Summer",
        "Lover",
        "The Man",
        "The Archer",
        "I Think He Knows",
        "Miss Americana & The Heartbreak Prince",
        "Paper Rings",
        "Cornelia Street",
        "Death by a Thousand Cuts",
        "London Boy",
        "Soon You'll Get Better (featuring Dixie Chicks)",
        "False God",
        "You Need to Calm Down",
        "Afterglow",
        "ME! (featuring Brendon Urie of Panic! At The Disco)",
        "It's Nice to Have a Friend",
        "Daylight"
      ]
    },
    {
      "image": "assets/images/Lover.png",
      "artistName": "Taylor Swift",
      "albumName": "Lover",
      "numberofSongs": 18,
      "songs": [
        "I Forgot That You Existed",
        "Cruel Summer",
        "Lover",
        "The Man",
        "The Archer",
        "I Think He Knows",
        "Miss Americana & The Heartbreak Prince",
        "Paper Rings",
        "Cornelia Street",
        "Death by a Thousand Cuts",
        "London Boy",
        "Soon You'll Get Better (featuring Dixie Chicks)",
        "False God",
        "You Need to Calm Down",
        "Afterglow",
        "ME! (featuring Brendon Urie of Panic! At The Disco)",
        "It's Nice to Have a Friend",
        "Daylight"
      ]
    },
  ].obs;
}
